title: Classification
description: Binary classification
theme: just-the-docs
#logo: "your_logo_path"
#favicon_ico: "your_icon_path"
url: https://github.com/ranja-sarkar/Classification
aux_links:
  Repository: https://github.com/ranja-sarkar/Classification
