title: Classification
description: 
theme: mybook
#logo: "your_logo_path"
#favicon_ico: "your_icon_path"
url: https://github.com/ranja-sarkar/mybook2
aux_links:
  Repository: https://github.com/ranja-sarkar/mybook2
